M48
; DRILL file {KiCad 6.0.11+dfsg-1} date Wed May 20 13:10:23 2026
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-20T13:10:23+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.325
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.775
%
G90
G05
T1
X75.847Y-110.955
X108.753Y-110.97
T2
X74.346Y-82.582
X74.346Y-89.782
T0
M30
